### ISSUE TITLE
Server not building.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#246]
It might be because it's late, but we managed to break the server without changing anything.

The error message I get when I run `./start.py -sc`, is:

>root@bot:~/bot2014/bot# ./start.py -sc
Starting server
Starting CLI
ctrl_server.py | __init__ | 94 | INFO | CtrlServer running in non-test mode
dmcc.py | __init__ | 68 | WARNING | Failed to verify DMCC at 0x2c
dmcc.py | __init__ | 68 | WARNING | Failed to verify DMCC at 0x2e
dmcc.py | __init__ | 68 | WARNING | Failed to verify DMCC at 0x2f
dmcc_motor.py | __init__ | 56 | ERROR | Bad motor definition for motor: 'back_right'
Traceback (most recent call last):
  File "./bot/server/ctrl_server.py", line 309, in <module>
    server = CtrlServer(sys.argv[1])
  File "./bot/server/ctrl_server.py", line 111, in __init__
    self.systems = self.assign_subsystems()
  File "./bot/server/ctrl_server.py", line 130, in assign_subsystems
    self.follower = Follower()
  File "/root/bot2014/bot/follower/follower.py", line 35, in __init__
    self.driver = mec_driver_mod.MecDriver()
  File "/root/bot2014/bot/driver/mec_driver.py", line 35, in __init__
    self.motors = DMCCMotorSet(motor_config)
  File "/root/bot2014/bot/hardware/dmcc_motor.py", line 57, in __init__
    raise KeyError

It was working earlier in the day, the same error message happens on `master`, `ADC_dev`, `follower_dev` (after fixing a lot of syntax errors).

I feel like I'm missing something obvious, but it's late.

**Comment by AhmedSamara** [comment]
After updating (`sudo apt-get update`) it started working again.

Exact cause still unknown.
